name: green-gift-tree
app: node@18
options:
  git:
    branch: main
    url: https://github.com/kingryan9996/green-gift-back
  env:
    - name: NODE_ENV
      value: production
  install: npm ci --production
  ports: 4000
  start: npm start
